### ISSUE TITLE
Null Pointer on running SS7 Firewall

### ISSUE THREAD

**Issue by chrispatt454** [P1sec/SigFW#21]
Hi All,

I finally managed to build this project without build errors on Ubuntu 20, but when I try to run the FW with this command:
mvn exec:java -Dexec.mainClass="ss7fw.SS7Firewall

It stalls with the below null pointers:

s7fw.SS7Firewall main
SEVERE: null
java.lang.NullPointerException
	at ss7fw.SS7Firewall.main(SS7Firewall.java:2566)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:829)

Has anyone seen this before, or able to help?

Thanks

Chris

**Comment by chrispatt454** [comment]
Full output of run to null pointers:

INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.p1sec:SigFW >---------------------------
[INFO] Building SigFW :: SigFW core 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ SigFW ---
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
May 20, 2022 3:18:24 P.M. org.glassfish.jersey.server.wadl.WadlFeature configure
WARNING: JAXBContext implementation could not be found. WADL feature is disabled.
0    [ss7fw.SS7Firewall.main()] INFO  ss7fw.SS7Firewall  - Trying to load SigFW extensions from: file:///home/chris/SigFW/sigfw/sigfw.sigfw/src/main/resources/SigFW_extension-1.0.jar
3    [ss7fw.SS7Firewall.main()] INFO  ss7fw.SS7Firewall  - Failed to load SigFW extensions: java.lang.ClassNotFoundException: com.p1sec.sigfw.SigFW_extension.rules.ExtendedFirewallRules
50   [ss7fw.SS7Firewall.main()] INFO  org.mobicents.protocols.sctp.netty.NettySctpManagementImpl  - SCTP configuration file path XmlSctpFirewall/sctp_mgmt_sctp.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0 (file:/root/.m2/repository/io/netty/netty-all/4.0.33.Final/netty-all-4.0.33.Final.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
167  [ss7fw.SS7Firewall.main()] INFO  io.netty.util.internal.PlatformDependent  - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
191  [ss7fw.SS7Firewall.main()] WARN  org.mobicents.protocols.sctp.netty.NettySctpManagementImpl  - Failed to load the SCTP configuration file. 
XmlSctpFirewall/sctp_mgmt_sctp.xml (No such file or directory)
198  [ss7fw.SS7Firewall.main()] INFO  org.mobicents.protocols.sctp.netty.NettySctpManagementImpl  - Started SCTP Management=sctp_mgmt
230  [ss7fw.SS7Firewall.main()] INFO  org.mobicents.protocols.sctp.netty.NettySctpManagementImpl  - Created Server=sctp_server
233  [ss7fw.SS7Firewall.main()] INFO  org.mobicents.protocols.sctp.netty.NettySctpManagementImpl  - Added Associoation=sctp_from_client_to_firewall of type=SERVER
243  [ss7fw.SS7Firewall.main()] INFO  org.mobicents.protocols.sctp.netty.NettySctpManagementImpl  - Added Associoation=sctp_from_firewall_to_server of type=CLIENT
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.sctp.nio.NioSctpServerChannel
	at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:455)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:306)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:271)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:267)
	at org.mobicents.protocols.sctp.netty.NettyServerImpl.initSocket(NettyServerImpl.java:302)
	at org.mobicents.protocols.sctp.netty.NettyServerImpl.start(NettyServerImpl.java:241)
	at org.mobicents.protocols.sctp.netty.NettySctpManagementImpl.startServer(NettySctpManagementImpl.java:667)
	at ss7fw.SS7Firewall.initSCTP(SS7Firewall.java:558)
	at ss7fw.SS7Firewall.initializeStack(SS7Firewall.java:854)
	at ss7fw.SS7Firewall.main(SS7Firewall.java:2557)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedOperationException: libsctp.so.1: cannot open shared object file: No such file or directory
	at jdk.sctp/sun.nio.ch.sctp.SctpNet.socket0(Native Method)
	at jdk.sctp/sun.nio.ch.sctp.SctpNet.socket(SctpNet.java:85)
	at jdk.sctp/sun.nio.ch.sctp.SctpServerChannelImpl.<init>(SctpServerChannelImpl.java:97)
	at jdk.sctp/com.sun.nio.sctp.SctpServerChannel.open(SctpServerChannel.java:106)
	at io.netty.channel.sctp.nio.NioSctpServerChannel.newSocket(NioSctpServerChannel.java:53)
	at io.netty.channel.sctp.nio.NioSctpServerChannel.<init>(NioSctpServerChannel.java:66)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:453)
	... 11 more
May 20, 2022 3:18:25 P.M. ss7fw.SS7Firewall main
SEVERE: null
java.lang.NullPointerException
	at ss7fw.SS7Firewall.main(SS7Firewall.java:2566)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by p1-martin** [comment]
Here are the build instructions https://github.com/P1sec/SigFW/wiki/Installation-and-Build-Instructions.

From the output you provided, check if you have installed all dependencies. Try the following:
`sudo apt-get install libsctp-dev lksctp-tools`

**Comment by chrispatt454** [comment]
Thanks so much Martin! That's done it, I missed those dependencies, my apologies, and thanks again!!

**Comment by p1-martin** [comment]
Happy to help you Chris. I will close this issue now.
